# Statically link the MSVC runtime for Windows release builds.
# Statically link the MSVC C runtime so users don't need VC++ Redistributable
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
