pub mod audio_commands;
pub mod context_commands;
pub mod credential_commands;
pub mod gemini_cache_commands;
pub mod intelligence_commands;
pub mod llm_commands;
pub mod local_runtime_commands;
pub mod meeting_commands;
pub mod model_commands;
pub mod settings_commands;
pub mod stealth_commands;
pub mod stt_commands;
pub mod rag_commands;
pub mod recording_commands;
pub mod translation_commands;
pub mod translation_model_commands;
pub mod tray_commands;
pub mod updater_commands;
pub mod mvp_commands;
mod practice_protocol;
mod answer_stream;
